### PR TITLE
django 1.7 support

### PR DESCRIPTION
**Pull request by imposeren**
Seems that there is no much to changed for 1.7 support:

1. moved south migrations to separate foleder
2. added info on South support
3. specified default for boolean field (it's set to None in 1.7 instead of False_

### CODE REVIEW

**Comment by wreckage** [comment]
Thank you for your interest and the work you've done on the project! I've been away from programming for some time now (~8 months) busy with school, and so I've unfortunately forgotten how many things work around here. I'd like to merge in your pull request, but it's telling me that the Travis CI build failed. Have you looked into why? Have you written tests to test out the changes you've made? I remember when I was creating the project I made sure to write as many tests as I could to test as much as possible, though clearly some things slipped by!

**Comment by imposeren** [comment]
1. Tests fail here:
```
Traceback (most recent call last):
  File "/home/travis/build/wreckage/django-happenings/tests/unit_tests/test_utils/test_clean.py", line 64, in test_invalid_out_of_bounds_year
    self.assertEqual(year, 2014)
AssertionError: 2015 != 2014
```

I have not changed anything related to this test. And I have no idea why it fails: code seems to be correct

2. Many changes I made depend on non-ascii locale which must be present on testing system. And I do not know how to add extra locales to travis CI image. So I have not tested my new changes

Short summary of changes:
1. Fixed several places that caused UnicodeDecodeError when non-ascii locales were used. Do not know how to test
2. CALENDAR_TIME_FORMAT can be set in settings. For example: ``CALENDAR_TIME_FORMAT = '%H:%M'``. Trivial change. Tests may be added but are they realy required here?
3. added method get_month_events that replaces ``list(Event.objects.all_month_events(year, month, self.category, self.tag, loc=True, cncl=True))``. This allows to easier modify behaviour in subclasses. I don't think that tests are required here.

Example usage:
https://bitbucket.org/imposeren/tabletop-planning/src/51834cdb7d217c53d1b2d65b5263a17a8e7aba6b/games/views.py?at=master#cl-290

4. fixed issue with events on last day of month: they were excluded from calendar. This can easily be tested but I have not added test for this
5. added django 1.7 migrations. moved south migrations to south_migrations. Added docs about this change to readme

**Comment by imposeren** [comment]
i've found source of error:
https://github.com/wreckage/django-happenings/blob/master/happenings/utils/common.py#L160
https://github.com/wreckage/django-happenings/blob/master/happenings/utils/common.py#L110

year is always set to now.year

**Comment by imposeren** [comment]
tests now pass.

**Comment by wreckage** [comment]
Thank you! Yesterday I merged in your pull request, and just now I pushed up a test to cover the issue you resolved involving the event that spans 2 months. Thanks again

**Pull request merged**
